In [1]:
import pandas as pd
import numpy as np
import datetime as dt
from sqlalchemy import create_engine

In [2]:
abhishek_all_tables = pd.read_excel(r"C:/Users/abhis/OneDrive/Documents/abhishek/Data_Analyst_Abhishek/data_analyst/Complete Projects/Stock Market Analysis/data/Abhishek_01-01-2021_14-09-2026.xlsx",sheet_name = None)

In [ ]:
abhishek_all_tables.items()

In [5]:
for i,k in abhishek_all_tables.items():
    # print(f"{i} name and value - {k}")
    print(f"{i} name")

Trade Level name
Realised Trade Level name
Unrealised Trade Level name
Realised Script Level name
Unrealised Script Level name

In [6]:
abhishek_realised_trade_level = abhishek_all_tables['Realised Trade Level']
abhishek_unrealised_trade_level = abhishek_all_tables['Unrealised Trade Level']
abhishek_realised_script_level = abhishek_all_tables['Realised Script Level']
abhishek_unrealised_script_level = abhishek_all_tables['Unrealised Script Level']
abhishek_trade_level = abhishek_all_tables['Trade Level']

In [ ]:
# Realised Script Level
abhishek_realised_script_level.columns
abhishek_realised_script_level.tail()
(abhishek_realised_script_level['Sell value'] - abhishek_realised_script_level['Buy value']).sort_values(ascending=False)
abhishek_realised_script_level['p_l_statement'] = np.where(abhishek_realised_script_level['Realised P&L'] >= 1.0,"Profit","Loss")
abhishek_realised_script_level.columns
abhishek_realised_script_level['p_l_statement'].value_counts()
abhishek_realised_script_level.groupby(abhishek_realised_script_level['p_l_statement'],as_index=False)[['Quantity','Buy value','Sell value','Realised P&L']].sum()

,Stock name,ISIN,Quantity,Buy date,Buy price,Buy value,Sell date,Sell price,Sell value,Realised P&L,Remark
0,PUNJAB NATIONAL BANK,INE160A01022,1,20-05-2021,36.50,36.50,20-05-2021,36.8,36.8,0.30,Intraday trade
1,NHPC LTD,INE848E01016,2,23-01-2024,77.00,154.00,04-06-2024,98.0,196.0,42.00,NaN
2,INDIAN RAILWAY FIN CORP L,INE053F01010,2,23-01-2024,162.80,325.60,13-06-2024,176.6,353.2,27.60,NaN
3,RATTANINDIA POWER LIMITED,INE399K01017,10,25-01-2024,10.25,102.50,04-06-2024,19.1,191.0,88.50,NaN
4,SUZLON ENERGY LIMITED,INE040H01021,5,25-01-2024,41.25,206.25,05-06-2024,49.0,245.0,38.75,NaN

In [ ]:
# abhishek_realised_trade_level
abhishek_realised_trade_level.head()
abhishek_realised_trade_level['Remark'] = abhishek_realised_trade_level['Remark'].fillna("No Data")
abhishek_realised_trade_level['Remark'].isna().value_counts()
abhishek_realised_trade_level['P_L_Statement'] = np.where(abhishek_realised_trade_level['Realised P&L'] >= 1, "Profit" , "Loss")
abhi_realised_trade_by_profit_category = abhishek_realised_trade_level.groupby(abhishek_realised_trade_level['P_L_Statement'],as_index=False)[['Quantity', 'Buy value',"Sell value", "Realised P&L"]].sum().sort_values("Realised P&L" , ascending=False)
abhi_realised_trade_by_stock = abhishek_realised_trade_level.groupby(abhishek_realised_trade_level['Stock name'], as_index=False)[['Quantity', 'Buy value',"Sell value", "Realised P&L"]].sum().sort_values("Realised P&L", ascending=False)

Remark
False    66
Name: count, dtype: int64

In [45]:
abhishek_realised_trade_level.head()

,Stock name,ISIN,Quantity,Buy date,Buy price,Buy value,Sell date,Sell price,Sell value,Realised P&L,Remark
0,PUNJAB NATIONAL BANK,INE160A01022,1,20-05-2021,36.50,36.50,20-05-2021,36.8,36.8,0.30,Intraday trade
1,NHPC LTD,INE848E01016,2,23-01-2024,77.00,154.00,04-06-2024,98.0,196.0,42.00,No Data
2,INDIAN RAILWAY FIN CORP L,INE053F01010,2,23-01-2024,162.80,325.60,13-06-2024,176.6,353.2,27.60,No Data
3,RATTANINDIA POWER LIMITED,INE399K01017,10,25-01-2024,10.25,102.50,04-06-2024,19.1,191.0,88.50,No Data
4,SUZLON ENERGY LIMITED,INE040H01021,5,25-01-2024,41.25,206.25,05-06-2024,49.0,245.0,38.75,No Data